name: "AL Code Analysis"
description: "Runs CodeCop, UICop, and PerTenantExtensionCop analysis on AL code"

inputs:
  project-path:
    description: "Path to the AL project"
    required: true
  package-cache-path:
    description: "Path to the AL package cache"
    required: true
  output-path:
    description: "Path for the compiled output"
    required: true
  ruleset-path:
    description: "Path to the AL ruleset"
    required: false
    default: ".alcop/ruleset.json"

runs:
  using: "composite"
  steps:
    - name: Download AL Language v11
      shell: pwsh
      run: |
        $alDownloadUrl = "https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/11.1.913972/1707813180141/Microsoft.Dynamics.Nav.Language.vsix"
        $vsixPath = "$env:RUNNER_TEMP\al_language.vsix"
        $extractPath = "$env:RUNNER_TEMP\al"

        Write-Host "⬇️ Downloading AL Language v11 from: $alDownloadUrl"
        Invoke-WebRequest -Uri $alDownloadUrl -OutFile $vsixPath
        Expand-Archive -Path $vsixPath -DestinationPath $extractPath -Force

        $alPath = Join-Path -Path $extractPath -ChildPath "extension\bin"
        echo "ALPATH=$alPath" >> $env:GITHUB_ENV
        Write-Host "✅ AL Language v11 extracted to: $alPath"

    - name: Run Code Analysis
      shell: pwsh
      run: |
        . "${{ github.action_path }}/src/script.ps1" `
          -ProjectPath "${{ inputs.project-path }}" `
          -PackageCachePath "${{ inputs.package-cache-path }}" `
          -Out
