name: "AL Code Analysis"
description: "Runs CodeCop, UICop, and PerTenantExtensionCop analysis on AL code"

inputs:
  project-path:
    description: "Path to the AL project"
    required: true
  package-cache-path:
    description: "Path to the AL package cache"
    required: true
  output-path:
    description: "Path for the compiled output"
    required: true
  ruleset-path:
    description: "Path to the AL ruleset"
    required: false
    default: ".alcop/ruleset.json"

runs:
  using: "composite"
  steps:
    - name: Download Latest AL Language Extension
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        
        $body = @{
          filters = @(
            @{
              criteria = @(
                @{ filterType = 7; value = "ms-dynamics-smb.al" }
              )
            }
          )
          flags = 0x1F
        } | ConvertTo-Json -Depth 10
        
        $headers = @{
          "Accept" = "application/json;api-version=3.0-preview.1"
          "Content-Type" = "application/json"
        }
        
        $response = Invoke-RestMethod `
          -Method Post `
          -Uri "https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery" `
          -Headers $headers `
          -Body $body
        
        $vsixUrl = $response.results[0].extensions[0].versions[0].files `
          | Where-Object { $_.assetType -eq "Microsoft.VisualStudio.Services.VSIXPackage" } `
          | Select-Object -ExpandProperty source
        
        Write-Host "⬇️ Downloading AL Language extension from: $vsixUrl"
        
        $vsixPath = "$env:RUNNER_TEMP\al_language.vsix"
        $extractPath = "$env:RUNNER_TEMP\al"
        
        Invoke-WebRequest -Uri $vsixUrl -OutFile $vsixPath
        Expand-Archive -Path $vsixPath -DestinationPath $extractPath -Force
        
        $alPath = Join-Path -Path $extractPath -ChildPath "extension\bin"
        echo "$alPath" >> $env:GITHUB_PATH
        Write-Host "✅ AL Language extension extracted to: $alPath"

    - name: Run Code Analysis
      shell: pwsh
      run: |
        . "${{ github.action_path }}/src/script.ps1" `
          -ProjectPath "${{ inputs.project-path }}" `
          -PackageCachePath "${{ inputs.package-cache-path }}" `
          -OutputPath "${{ inputs.output-path }}" `
          -RulesetPath "${{ inputs.ruleset-path }}"

    - name: Upload Code Analysis Results
      uses: actions/upload-artifact@v4
      with:
        name: code-analysis-results
        path: "${{ inputs.output-path }}"
        retention-days: 30